name: coffee_app
description: A Flutter project to request coffee and more with a fluid and intuitive experience.

version: 1.0.0

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #
  rxdart: ^0.22.1
  get_it: ^1.0.3+2
  flutter_i18n: ^0.6.3
  shared_preferences: ^0.5.3+4
  http_interceptor: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/
